# Dependencies
markdown:         kramdown
highlighter:      rouge
kramdown:
  auto_ids: true
# Permalinks
permalink:        pretty
# Server
destination:      _gh_pages
baseurl:          ""
url:              https://ajaxlivesearch.xyz
encoding:         UTF-8
exclude:          [assets/scss/]
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
